# Generated by Django 4.0.5 on 2022-06-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_content', models.CharField(max_length=10000)),
                ('request_date', models.DateTimeField()),
                ('response_content', models.CharField(max_length=10000)),
            ],
        ),
    ]
